apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-storage-scheduler
  namespace: orchestration
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ai-storage-scheduler
      namespace: orchestration
  template:
    metadata:
      labels:
        name: ai-storage-scheduler
        namespace: orchestration
    spec:
      serviceAccountName: ai-storage-scheduler
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      imagePullSecrets:
        - name: regcred
      containers:
        - name: ai-storage-scheduler
          image: ketidevit2/ai-storage-scheduler:v0.0.1
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
                requests:
                  memory: "128Mi"
                  cpu: "250m"    
                limits:
                  memory: "1Gi" 
                  cpu: "1"
          volumeMounts:
            - name: tz-config
              mountPath: /usr/share/zoneinfo/Asia/Seoul
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-storage-scheduler
  namespace: orchestration
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ai-storage-scheduler-crb
subjects:
- kind: ServiceAccount
  name: ai-storage-scheduler
  namespace: orchestration
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io