apiVersion: v1
kind: Pod
metadata:
  name: test-gpu-pod
  namespace: keti
  labels:
    app: gpu-test
spec:
  schedulerName: ai-storage-scheduler
  containers:
  - name: gpu-container
    image: busybox:latest
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
        nvidia.com/gpu: "1"
      limits:
        cpu: "1000m"
        memory: "1Gi"
        nvidia.com/gpu: "1"
  restartPolicy: Never
