apiVersion: v1
kind: Pod
metadata:
  name: simple-gpu-pod
  namespace: keti
spec:
  schedulerName: ai-storage-scheduler
  restartPolicy: Never
  containers:
  - name: gpu-test
    image: busybox:latest
    command: ["sh", "-c", "echo 'GPU Pod on node:' && cat /etc/hostname && sleep 300"]
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
        nvidia.com/gpu: "1"
      limits:
        cpu: "200m"
        memory: "256Mi"
        nvidia.com/gpu: "1"
