apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-pod
  namespace: keti
  labels:
    app: gpu-test
    test: scheduler-debug
spec:
  schedulerName: ai-storage-scheduler
  restartPolicy: Never
  containers:
  - name: gpu-container
    image: nvidia/cuda:11.8.0-base-ubuntu22.04
    command:
      - "bash"
      - "-c"
      - |
        echo "==================================="
        echo "GPU Test Pod Started"
        echo "==================================="
        echo "Node: $NODE_NAME"
        echo "Pod: $POD_NAME"
        echo "Namespace: $POD_NAMESPACE"
        echo "==================================="
        nvidia-smi || echo "nvidia-smi not available"
        echo "==================================="
        echo "Sleeping for 3600 seconds..."
        sleep 3600
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
        nvidia.com/gpu: "1"
      limits:
        cpu: "1000m"
        memory: "1Gi"
        nvidia.com/gpu: "1"
