apiVersion: v1
kind: Pod
metadata:
  name: no-gpu-test-pod
  namespace: keti
  labels:
    app: no-gpu-test
    test: scheduler-debug
spec:
  schedulerName: ai-storage-scheduler
  restartPolicy: Never
  containers:
  - name: cpu-container
    image: busybox:latest
    command:
      - "sh"
      - "-c"
      - |
        echo "==================================="
        echo "No-GPU Test Pod Started"
        echo "==================================="
        echo "Node: $NODE_NAME"
        echo "Pod: $POD_NAME"
        echo "This pod does NOT request GPU"
        echo "==================================="
        echo "Sleeping for 3600 seconds..."
        sleep 3600
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
